//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerMagazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string login { get; set; }
        public string password { get; set; }
        public string First_name { get; set; }
        public string Second_name { get; set; }
        public string Surname { get; set; }
        public int id_role { get; set; }
    
        public virtual role role { get; set; }
    }
}
