//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerMagazin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerMagazinEntities : DbContext
    {
        public ComputerMagazinEntities()
            : base("name=ComputerMagazinEntities")
        {
        }

        private static ComputerMagazinEntities _context;

        public static ComputerMagazinEntities GetContext()
        {
            if (_context == null)
                _context = new ComputerMagazinEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<pc_Body> pc_Body { get; set; }
        public virtual DbSet<pc_category> pc_category { get; set; }
        public virtual DbSet<pc_CPU> pc_CPU { get; set; }
        public virtual DbSet<pc_features_default> pc_features_default { get; set; }
        public virtual DbSet<pc_features_personal> pc_features_personal { get; set; }
        public virtual DbSet<pc_GPU> pc_GPU { get; set; }
        public virtual DbSet<pc_HDD> pc_HDD { get; set; }
        public virtual DbSet<pc_RAM> pc_RAM { get; set; }
        public virtual DbSet<pc_SSD> pc_SSD { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<TableForComboBox> TableForComboBox { get; set; }
        public virtual DbSet<TableForSavePictures> TableForSavePictures { get; set; }
        public virtual DbSet<type_OC> type_OC { get; set; }
    }
}
