//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerMagazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableForComboBox
    {
        public int id_combobox { get; set; }
        public string select_combobox { get; set; }
    }
}
